Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2022
Var
// Seção de Declarações das variáveis 
c,temperaturaF:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(temperaturaF)
c <- 5*((temperaturaF -32 )/9)
escreval(c)
Fimalgoritmo