Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2022
Var
// Seção de Declarações das variáveis 
centimetros,metros:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

leia(metros)
centimetros <- metros*100
escreval(centimetros)

Fimalgoritmo